DROP TABLE IF EXISTS participate;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS university;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS contest;
DROP TABLE IF EXISTS site;
DROP TABLE IF EXISTS region;
